site_name: DotFiles - My Personal Site
site_description:

repo_name: DotFiles
repo_url: https://github.com/Mohamed-Kaizen/dotfiles
edit_uri:

copyright: Copyright &copy; 2021 Mohamed Nesredin

theme:
  palette:
    scheme: slate
    primary: deep orange
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  features:
    # - navigation.tabs
    # - navigation.instant # uncommon this if you don't want SPA mode

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago

nav:
  - Home: "index.md"
  - Zorin OS: "zorin.md"

markdown_extensions:
  - meta
  - abbr
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tabbed
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra_css:
  - "css/termynal.css"
  - "css/custom.css"

extra_javascript:
  - "js/mermaid.min.js"
  - "js/termynal.js"
  - "js/custom.js"
